from sqlalchemy import String, Integer, DateTime, Date

class Matches():

    composite_keys = ["competition_id", "season_id", 'match_id']

    column_mapping = {
        'match_id': Integer, 
        'match_date': Date, 
        'kick_off': String, 
        'home_score': Integer, 
        'away_score': Integer,
        'match_status': String, 
        'match_status_360': String, 
        'last_updated': DateTime, 
        'last_updated_360': DateTime,
        'match_week': String, 
        'competition_id': Integer, 
        'competition_country_name': String,
        'competition_name': String, 
        'competition': String, 
        'season_id': Integer, 
        'season': String,
        'home_team_id': Integer, 
        'home_team': String, 
        'home_team_gender': String, 
        'home_team_group': String,
        'home_team_country_id': String, 
        'home_team_country_name': String, 
        'away_team_id': Integer,
        'away_team': String, 
        'away_team_gender': String, 
        'away_team_group': String,
        'away_team_country_id': Integer, 
        'away_team_country_name': String,
        'competition_stage_id': Integer, 
        'competition_stage': String, 
        'stadium_id': Integer, 
        'stadium': String,
        'stadium_country_id': Integer, 
        'stadium_country_name': String, 
        'referee_id': Integer, 
        'referee': String,
        'referee_country_id': Integer, 
        'referee_country_name': String, 
        'home_managers': String,
        'away_managers': String, 
        'home_manager_id': Integer, 
        'home_manager_name': String,
        'home_manager_nickname': String, 
        'home_manager_dob': String, 
        'home_manager_country_id': String,
        'home_manager_country_name': String, 
        'away_manager_id': Integer, 
        'away_manager_name': String,
        'away_manager_nickname': String, 
        'away_manager_dob': String, 
        'away_manager_country_id': String,
        'away_manager_country_name': String, 
        'data_version': String, 
        'shot_fidelity_version': String,
        'xy_fidelity_version': String
    }

    date_columns = ['last_updated', 'last_updated_360', 'match_date']